# Generated by Django 6.0.7 on 2026-07-15 15:08

import common.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='questline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questline',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers', validators=[common.validators.validate_image_size]),
        ),
    ]
