# Generated by Django 6.0.7 on 2026-07-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0002_alter_questline_options_questline_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
                ('prerequisite_quests', models.ManyToManyField(to='questlines.quest')),
                ('questline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questlines.questline')),
            ],
        ),
    ]
