# Generated by Django 6.0.7 on 2026-07-15 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0003_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='questline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='questlines.questline'),
        ),
    ]
