# Generated by Django 6.0.7 on 2026-07-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0004_alter_quest_questline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='coord_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='coord_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='prerequisite_quests',
            field=models.ManyToManyField(blank=True, to='questlines.quest'),
        ),
    ]
