# Generated by Django 6.0.7 on 2026-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0005_alter_quest_coord_x_alter_quest_coord_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='prerequisite_quests',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='questlines.quest'),
        ),
    ]
