# Generated by Django 6.0.7 on 2026-07-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0006_alter_quest_prerequisite_quests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=9999)),
                ('objective_type', models.CharField(editable=False, max_length=100)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='questlines.quest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistObjective',
            fields=[
                ('objective_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questlines.objective')),
            ],
            bases=('questlines.objective',),
        ),
        migrations.CreateModel(
            name='SliderObjective',
            fields=[
                ('objective_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questlines.objective')),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('target_value', models.IntegerField(default=50)),
            ],
            bases=('questlines.objective',),
        ),
    ]
