# Generated by Django 6.0.7 on 2026-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0007_objective_checklistobjective_sliderobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(blank=True, max_length=99999),
        ),
    ]
