# Generated by Django 6.0.7 on 2026-07-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0008_quest_description_alter_objective_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='note',
            field=models.TextField(blank=True, max_length=99999),
        ),
    ]
