# Generated by Django 6.0.7 on 2026-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0009_quest_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questline',
            name='visibility',
        ),
        migrations.AddField(
            model_name='questline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('private', 'Private'), ('published', 'Published')], default='draft', max_length=9),
        ),
    ]
