# Generated by Django 6.0.7 on 2026-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0010_remove_questline_visibility_questline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('private', 'Private'), ('public', 'Public')], default='draft', max_length=9),
        ),
    ]
