# Generated by Django 6.0.7 on 2026-07-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0011_alter_questline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questline',
            name='cover_image',
        ),
    ]
