# Generated by Django 6.0.7 on 2026-08-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questlines', '0012_remove_questline_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='note',
        ),
    ]
