# Generated by Django 6.0.7 on 2026-08-04 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questlines', '0013_remove_quest_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questlines.questline')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=99999)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questlines.quest')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('current_value', models.IntegerField(null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.enrollment')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questlines.objective')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('enrolled_user', 'questline'), name='unique_user_questline_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='adventurenote',
            constraint=models.UniqueConstraint(fields=('enrollment', 'quest'), name='unique_enrollment_quest'),
        ),
        migrations.AddConstraint(
            model_name='objectiveprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'objective'), name='unique_enrollment_objective'),
        ),
    ]
