# Generated by Django 6.0.7 on 2026-07-15 15:08

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_profile_picture_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', validators=[common.validators.validate_image_size]),
        ),
    ]
